-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- Link to schema: https://app.quickdatabasediagrams.com/#/d/SswuVB
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.


CREATE TABLE "NAICS_CODE" (
    "CODES" DEC   NOT NULL,
    "TITLES" VARCHAR   NOT NULL,
    CONSTRAINT "pk_NAICS_CODE" PRIMARY KEY (
        "CODES"
     )
);

CREATE TABLE "EMPLOYEE" (
    "CASE_NUMBER" VARCHAR   NOT NULL,
    "CASE_STATUS" VARCHAR  NOT NULL,
    "DECISION_DATE" DATE   NOT NULL,
    "EMP_ID" INT   NOT NULL,
    "NAIC_CODE" DEC   NOT NULL
);

CREATE TABLE "EMPLOYER" (
    "EMP_ID" INT   NOT NULL,
    "EMPLOYER_NAME" VARCHAR   NOT NULL,
    "EMPLOYER_CITY" VARCHAR  NOT NULL,
    "EMPLOYER_STATE" VARCHAR  NOT NULL,
    CONSTRAINT "pk_EMPLOYER" PRIMARY KEY (
        "EMP_ID"
     )
);

ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "fk_EMPLOYEE_NAIC_CODE" FOREIGN KEY("NAIC_CODE")
REFERENCES "NAICS_CODE" ("CODES");

ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "fk_EMPLOYEE_EMP_ID" FOREIGN KEY("EMP_ID")
REFERENCES "EMPLOYER" ("EMP_ID");

